// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAopELruB2v4uxMUz5SDbGcGBEb6fWQ_ew',
    appId: '1:867760205161:web:0638c848d3caeb684ae1f8',
    messagingSenderId: '867760205161',
    projectId: 'expense-tracker-e6346',
    authDomain: 'expense-tracker-e6346.firebaseapp.com',
    storageBucket: 'expense-tracker-e6346.appspot.com',
    measurementId: 'G-S2W1K813MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3X02XSmGfz2NRxZ-Ht7nJopGoprJCv4g',
    appId: '1:867760205161:android:5907ffdca8671f0c4ae1f8',
    messagingSenderId: '867760205161',
    projectId: 'expense-tracker-e6346',
    storageBucket: 'expense-tracker-e6346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3wENd-HMT0ddGk1ySUefr0odndyHegOs',
    appId: '1:867760205161:ios:b2fdaca41ce27f1e4ae1f8',
    messagingSenderId: '867760205161',
    projectId: 'expense-tracker-e6346',
    storageBucket: 'expense-tracker-e6346.appspot.com',
    iosBundleId: 'com.example.flutterApplicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3wENd-HMT0ddGk1ySUefr0odndyHegOs',
    appId: '1:867760205161:ios:b2fdaca41ce27f1e4ae1f8',
    messagingSenderId: '867760205161',
    projectId: 'expense-tracker-e6346',
    storageBucket: 'expense-tracker-e6346.appspot.com',
    iosBundleId: 'com.example.flutterApplicationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAopELruB2v4uxMUz5SDbGcGBEb6fWQ_ew',
    appId: '1:867760205161:web:7690a8be5c8da6f64ae1f8',
    messagingSenderId: '867760205161',
    projectId: 'expense-tracker-e6346',
    authDomain: 'expense-tracker-e6346.firebaseapp.com',
    storageBucket: 'expense-tracker-e6346.appspot.com',
    measurementId: 'G-JZ72GCT764',
  );
}
